dist: trusty
sudo: false
language: python
install:
  - pip install pybuilder
python:
  - "3.4"
  - "3.5"
  - "3.6"
script:
  - pyb analyze publish install
  - venv-bootstrap-install --version
  - mkdir github-release
  - cp target/dist/*/dist/*.tar.gz github-release
  - venv-bootstrap-install --no-interactive github-release
  - ls github-release
deploy:
  - provider: releases
    api_key:
      secure: fnx4Q/8sfmPbyx2FU/ZSoYCq2OwJKS7uiVCyuCGEvEXlyADMRRL2f4Fk7twnPLTJshaZSLE+K5PvU7wMirE6rk0VqC27VyFvaghIUwlyr/VwzgIMXEZUqthiQS/9GNnK927fecnB9NfCroYHcUVHOyxDQRGx0byezaHaq9UIlbDx1aCt5Sklo4qtijaxpL2VIqtLcuAitqC8uVKd2xXgSbPZtRYOvj9uxwsPDsKP+uh9M10ehQQMbUvXApftRJAE6GlXWSSlrnsRFgv/p2SEFKkGxwqP36W5DDIfJx+SOgkMWjchAG71zaFSV5f1mNJkVbdequV+WUCEz9/G+yqeBbz/r93A+WvJHhRex2OUYtRE6UtbqhD70+YLzlzpDYLrIPwO92YS2NpUN4diS94MVc0qTSn9fAt2mYSFQGdFiLThcmgQ/sQDJstkQRM6D3SdHWxTpzBEItFiJFztKh45uWiwPshzcZddq+ybnHZ+8pY2XChJ05SxxlMVpEU4KNSflNFjQG4lMLpQlvcHOssBmrkxMspZi+zCTJqoCOXpNOkxCdlz7RFmfUqb5HjvI6taDd1lrJUvdUatHkUgrIBoFG0nCfnaApaUNySr/n8K7XSNuIbKzS9MzZrfGgGRfZy9kOfK9WpKLEzubU6DnODhYBMwxcufvFbOa3Bf3N0QQKY=
    file_glob: true
    file: github-release/*
    skip_cleanup: true
    on:
      repo: kshpytsya/venv-bootstrap.py
      tags: true
      python: 3.6
  - provider: pypi
    user: kshpytsya
    password:
      secure: "dnSGNtRXfTlnCYZgmVy+Rn54taDGXYDw6rFRBtGxtojgJ5bu4KeTGSbfhz4H/YpLmFRHX4IRjyKHqYMW5QMphAULae9rsd/4z/HfQqoN3Utmidk6CZVkGt86g0BMJbDylZwKzjj/+ke1lBsPuUweIUVwXntYqYWkRN/T9L/RnFxMt3Mkwf+atGje/AZHwAfLECeNduwHHVh+xKiYADltmhRmIrUSV/lXBSTJsY6VPamN/N2mu4vmHaB5vPdZR/mwBaneUFOcCzzWfTapQgY+vn25hBBIy7ppzVDL908jlVOFDjqLMAxn6InHVA9MS7kYW3PmBlGlODw4cnUdRaxG5QyP3qm8FgVW55C4C5l0BsoougQ1jJj1CI54EgfT/OIV1BYVgBxpxxtdab2/5mdoI7rG+X63CJF7X7hZqLfk2e2bkuMNn+Ui56vOVSzwOpfPgj3QHNHOIGyeukuOrHA1eYj4lDTCw/AJOK1V8oxWQhN+IYUHce06Ok3UKJOtBDIDgAfhPMD+UpVkyb4m/2OnwTDy78DO9JwMWffY/Ir6tW7wVzp7+y7t+n/F7+V9F3gzmRYn3xdPxy2s/hD8UrJxUedQTf82N57zyishYutJwV/NNSNGdI3WYzeTjzP0J4uIHXi5s7brOQSaldhNXmLbF0XFOHS8bi9yh+s2J+5K4DE="
    on:
      repo: kshpytsya/venv-bootstrap.py
      tags: true
      python: 3.6
