environment:
    global:
        VERBOSE_SUBPROCESS: 1
    matrix:
        - PYTHON: "C:/Python34-x64"
        - PYTHON: "C:/Python35-x64"
        - PYTHON: "C:/Python36-x64"
install:
    - "pip3 install --disable-pip-version-check --user --upgrade pip"
    - "pip3 install pybuilder pybuilder_scm_ver_plugin"
build_script:
    - "pyb_ analyze publish install"
test_script:
    - "venv-bootstrap-install --version"
    - "mkdir testdir"
    - "venv-bootstrap-install --no-interactive testdir"
    - "python3 testdir/venv-bootstrap.py --version"
