shallow_clone: true
environment:
    global:
        VERBOSE_SUBPROCESS: 1
    matrix:
        - PYTHON: "C:/Python34-x64"
        - PYTHON: "C:/Python35-x64"
        - PYTHON: "C:/Python36-x64"
install:
    - "pip install --disable-pip-version-check --user --upgrade pip"
    - "pip install pybuilder"
    - "pyb_ analyze publish install"
    - "venv-bootstrap-install --version"
    - "mkdir testdir"
    - "venv-bootstrap-install --no-interactive github-release"
    - "python testdir/venv-bootstrap.py --version"
build: off
test_script:
    - "%PYTHON%/python -m unittest"
