shallow_clone: true
environment:
    global:
        VERBOSE_SUBPROCESS: 1
    matrix:
        - PYTHON: "C:/Python34-x64"
        - PYTHON: "C:/Python35-x64"
        - PYTHON: "C:/Python36-x64"
build: off
test_script:
    - "%PYTHON%/python -m unittest"
