environment:
    global:
        VERBOSE_SUBPROCESS: 1
    matrix:
        - PYTHON: "C:/Python34-x64"
        - PYTHON: "C:/Python35-x64"
        - PYTHON: "C:/Python36-x64"
init:
    - "set PATH=%PYTHON%/scripts;%PYTHON%;%PATH%"
    - "python --version"
    - "pip --version"
install:
    - "pip install --disable-pip-version-check --user --upgrade pip"
    - "pip install pybuilder pybuilder_scm_ver_plugin"
build_script:
    - "pyb_ install_dependencies analyze publish install"
test_script:
    - "venv-bootstrap-install --version"
    - "mkdir testdir"
    - "venv-bootstrap-install --no-interactive testdir"
    - "python testdir/venv-bootstrap.py --version"
