version: 2
jobs:
    build:
        macos:
            xcode: "9.0"
        steps:
            - checkout
            - run: brew install python3
            - run: python3 -V
            - run: pip3 install pybuilder
            - run: pyb analyze publish install
            - run: venv-bootstrap-install --version
            - run: mkdir testdir"
            - run: venv-bootstrap-install --no-interactive github-release
            - run: python3 testdir/venv-bootstrap.py --version
