version: 2
jobs:
    build:
        macos:
            xcode: "9.0"
        steps:
            - checkout
            - run: brew install python3
            - run: python3 -V
            - run: python3 venv-bootstrap.py --version
            - run: python3 venv-bootstrap.py --help
            - run: python3 -m unittest
